branches:
  only:
    - source
language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g hexo
install:
  - npm install
script:
  - hexo generate
after_success:
  - ls -la
  - git config --global push.default simple
  - git config --global user.name '6leaf'
  - git config --global user.email luzky12@gmail.com
  - git add -A
  - git commit -m 'update'
  - git push https://$GH_NAME:$GH_TOKEN@github.com/$GH_NAME/6leaf.github.io.git HEAD:master
  
env:
  global:
    secure: M4D6MYqCS7fJa4sD/owiCJKojHGsOmNYdfnGyKgzCEiajqjmcGk4TbW8TNojF5YIjNktVg2qrJqzhq3SmPQ16ris+BlAfulS80wA8JYKZ/FhMoMCXi/fNrU1X5YiiUvpCpswbpJh5GfLHLM6izjUWgwMHFjQpifDgwZ/j47Is88=
